---
title: "R Notebook"
output: html_notebook
---

# install packages

```{r}
#install.packages("tidyverse", dependencies = TRUE)
#install.packages("ggthemes", dependencies = TRUE)
```
#load packages
```{r}
library(tidyverse)
library(ggthemes)
```

# import data
```{r}
exp = read_csv("exp1.csv")
nrow(exp)
ncol(exp)
colnames(exp)
hist(exp$rt)
```
# tidyverse verbs
```{r}
condition_data = 
exp %>% 
  select(subject, rt, typeoftrial, trialcondition, correct) %>%
  filter(typeoftrial == "picture" &
           trialcondition %in%
           c("Heavy_Normal", "Light_Smashed", "Heavy_Smashed", "Light_Normal"))

means = condition_data %>% 
  group_by(trialcondition)%>%
  summarise(mean_rt = mean(rt), sd_rt = sd(rt), mean_acc = mean(correct))

library(ggplot2)
library(ggthemes)

condition_data %>% 
  filter(rt < 25000) %>%
  ggplot(aes(x = rt)) +
  geom_histogram(binwidth = 1000, 
                 fill = "red", 
                 color = "black", 
                 position = "identity") + 
  theme_few() +
  xlab("RT (in miliseconds)") + ylab ("Count") + ggtitle("Histogram of RT")

means %>%
  ggplot(aes(x = trialcondition, y = mean_rt)) +
  geom_bar(stat = "identity", fill = "pink", color = "navy") +
  theme_fivethirtyeight() +
  xlab("RT (in miliseconds)") + 
  ylab ("Count") + 
  ggtitle("Barplot of RT")
```
# class exercises
```{r}
df = read_csv("relatedness_exp.csv")
```
```{r}
part_df = 
df %>% 
  select(ID, Type, pathlength, RT) %>%
  filter(Type == "Related" &
           pathlength %in%
           c(1, 2))

mean_all = df %>% 
  summarise(mean_all = mean(RT))

mean_part = part_df %>% 
  summarise(mean_part = mean(RT))
            
mean_ID = df %>% group_by(ID) %>%
  summarise(mean_ID = mean(RT))



```
  
  
#exp %>% 
 # select(dataset, correct, typeoftrial) %>%
 # filter(correct == 1 & typeoftrial == "picture")
```

